# NumPy基本

In [1]:
import numpy as np
import matplotlib.pyplot as plt

#### 配列
プログラムでの"次元"とは、インデックスの総数のこと。  
例えば、$a_{ij}$で表される配列を二次元とする。  
そのため、数学での次元とは意味が異なる。

In [36]:
x = np.array([1,2,3,4,5])
print("======array=======")
print("x=" + str(x))
print(x.dtype)
x[:-1]
print(x[0])
print(x[1:4])
print(x[1:-2])

print("=======arange=======")
x = np.arange(5)
print("x=" + str(x))
print(x.dtype)
x = np.arange(1, 10, 2, dtype=np.float128) 
print("x=" + str(x))
print(x.dtype)

print("=======2次元=======")
x = np.array([[1,2,3], [4,5,6]])
print("x=" + str(x))
for i in range(2):
    for j in range(3):
        print("x[" + str(i) + ", " + str(j) + "]=" + str(x[i, j]))

======array=======
x=[1 2 3 4 5]
int64
1
[2 3 4]
[2 3]
=======arange=======
x=[0 1 2 3 4]
int64
x=[1. 3. 5. 7. 9.]
float128
=======2次元=======
x=[[1 2 3]
 [4 5 6]]
x[0, 0]=1
x[0, 1]=2
x[0, 2]=3
x[1, 0]=4
x[1, 1]=5
x[1, 2]=6


#### 配列の属性

In [2]:
x = np.arange(15.).reshape(3,5)
print(x)
print(x.shape)
print(x.ndim)
print(x.size)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
(3, 5)
2
15


In [10]:
x = np.arange(10)
y = np.arange(20, 30)
print(x)
print(y)
print(x+y)
print(x*y)
print(np.dot(x, y))
print((x*y).sum())

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29]
[20 22 24 26 28 30 32 34 36 38]
[  0  21  44  69  96 125 156 189 224 261]
1185
1185
