# NumPy基本

In [62]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import sparse 
from scipy import linalg

#### 配列
プログラムでの"次元"とは、インデックスの総数のこと。  
例えば、$a_{ij}$で表される配列を二次元とする。  
そのため、数学での次元とは意味が異なる。

In [36]:
x = np.array([1,2,3,4,5])
print("======array=======")
print("x=" + str(x))
print(x.dtype)
x[:-1]
print(x[0])
print(x[1:4])
print(x[1:-2])

print("=======arange=======")
x = np.arange(5)
print("x=" + str(x))
print(x.dtype)
x = np.arange(1, 10, 2, dtype=np.float128) 
print("x=" + str(x))
print(x.dtype)

print("=======2次元=======")
x = np.array([[1,2,3], [4,5,6]])
print("x=" + str(x))
for i in range(2):
    for j in range(3):
        print("x[" + str(i) + ", " + str(j) + "]=" + str(x[i, j]))

======array=======
x=[1 2 3 4 5]
int64
1
[2 3 4]
[2 3]
=======arange=======
x=[0 1 2 3 4]
int64
x=[1. 3. 5. 7. 9.]
float128
=======2次元=======
x=[[1 2 3]
 [4 5 6]]
x[0, 0]=1
x[0, 1]=2
x[0, 2]=3
x[1, 0]=4
x[1, 1]=5
x[1, 2]=6


#### 配列の属性

In [2]:
x = np.arange(15.).reshape(3,5)
print(x)
print(x.shape)
print(x.ndim)
print(x.size)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
(3, 5)
2
15


In [2]:
x = np.arange(10)
y = np.arange(20, 30)
print(x)
print(y)
print(x+y)
print(x*y)
print(np.dot(x, y))
print((x*y).sum())

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29]
[20 22 24 26 28 30 32 34 36 38]
[  0  21  44  69  96 125 156 189 224 261]
1185
1185


#### 疎行列

多くの要素が0であるような行列を**疎行列**、通常の行列を**密行列**と表現することがある。  
疎行列に値を随時入れなおすような場合は、`lil_matrix`型が便利。  
しかし、計算処理が遅いので、速度を求める場合は`csr_matrix`や`csc_matrix`型に変換する。  
なお、後者の2つの型は、随時値を設定することができない。

In [43]:
# 疎行列の生成
a = sparse.lil_matrix((4, 5))
# この時点では全て空になっている
print(a.toarray())
a[0, 1] = 1
a[1, 2] = 2
a[2, 3] = 3
a[3, 3] = 4
print(a)
# 密行列へ変換
print(a.toarray())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
  (0, 1)	1.0
  (1, 2)	2.0
  (2, 3)	3.0
  (3, 3)	4.0
[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 4. 0.]]


In [42]:
# 疎行列の生成
b = sparse.lil_matrix((5, 4))
b[0, 1] = 1
b[1, 2] = 2
b[2, 3] = 3
b[3, 3] = 4
# 配列へ変換
print(b.toarray())

[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]]


In [44]:
#　行列積
c = a.dot(b)
print(c)
print(c.toarray())

  (0, 2)	2.0
  (1, 3)	6.0
  (2, 3)	12.0
  (3, 3)	16.0
[[ 0.  0.  2.  0.]
 [ 0.  0.  0.  6.]
 [ 0.  0.  0. 12.]
 [ 0.  0.  0. 16.]]


In [49]:
A = a.tocsr()
B = b.tocsr()
C = A.dot(B)
print(C.toarray())

[[ 0.  0.  2.  0.]
 [ 0.  0.  0.  6.]
 [ 0.  0.  0. 12.]
 [ 0.  0.  0. 16.]]


#### 逆行列
NumPyで逆行列を求めるには`linalg.inv`関数を使う。  

In [60]:
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])
print(a)
print("逆行列======>>>")
print(np.linalg.inv(a))

[[ 3  1  1]
 [ 1  2  1]
 [ 0 -1  1]]
逆行列======>>>
[[ 0.42857143 -0.28571429 -0.14285714]
 [-0.14285714  0.42857143 -0.28571429]
 [-0.14285714  0.42857143  0.71428571]]


#### LU分解
一般に、素直に逆行列を求めるより、LU分解による計算の方が、計算量が少なく、なおかつ数値的に安定している、らしい。
$$
\boldsymbol{Ax} = \boldsymbol{b}
$$
を次に変換。
$$
\boldsymbol{PLUx} = \boldsymbol{b}
$$
[wiki](https://ja.wikipedia.org/wiki/LU%E5%88%86%E8%A7%A3#:~:text=%E6%95%B0%E5%AD%A6%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E8%A1%8C%E5%88%97%E3%81%AELU,%E3%82%92%E6%B1%82%E3%82%81%E3%82%8B%E3%81%93%E3%81%A8%E3%82%92%E3%81%84%E3%81%86%E3%80%82)
と[参考文献](https://opqrstuvcut.github.io/blog/posts/%E5%AE%89%E6%98%93%E3%81%AB%E9%80%86%E8%A1%8C%E5%88%97%E3%82%92%E6%95%B0%E5%80%A4%E8%A8%88%E7%AE%97%E3%81%99%E3%82%8B%E3%81%AE%E3%81%AF%E3%82%84%E3%82%81%E3%82%88%E3%81%86/)

In [80]:
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])
b = np.array([1,2,3])
print("a==========>")
print(a)
print("b==========>")
print(b)
lu, p = linalg.lu_factor(a)
print("lu==========>")
print(lu)
print("p==========>")
print(p)
print("解==========>")
print(linalg.lu_solve((lu, p), b))

#　本当に解になっているか
print("検証==========>")
print(a.dot(linalg.lu_solve((lu, p), b).T))

a==========>
[[ 3  1  1]
 [ 1  2  1]
 [ 0 -1  1]]
b==========>
[1 2 3]
lu==========>
[[ 3.          1.          1.        ]
 [ 0.33333333  1.66666667  0.66666667]
 [ 0.         -0.6         1.4       ]]
p==========>
[0 1 2]
解==========>
[-0.57142857 -0.14285714  2.85714286]
検証==========>
[1. 2. 3.]
